### ISSUE TITLE
Cannot access ambient const enums when run by `tsx` but no problem by `ts-node`

### ISSUE THREAD

**Issue by WankkoRee** [privatenumber/ts-runtime-comparison#16]
### Problem

I declare enum in typings like it:

```ts
// src/typings/main/index.d.ts

declare const enum Test {
  hello = 'world',
}
```

and `tsconfig.json` like it:

```json
{
  "compilerOptions": {
    "typeRoots": ["src/typings"]
  }
}
```

and then I try to use enums like it:

```ts
// src/main.ts

console.log(Test.hello);
```

then it will be `ReferenceError: Test is not defined`.

### Expected behavior

print `world` just like if I run it by `ts-node`.

I run it by `ts-node` without problem, so I think may it is a bug for `tsx` ?

ts-node behavior: https://codesandbox.io/p/sandbox/tsx-bug-in-ts-node-r9h985

tsx behavior: https://codesandbox.io/p/sandbox/tsx-bug-rl55dz

> because `StackBlitz` does not support `ts-node`, I use `CodeSandbox`.

### Minimal reproduction URL

https://codesandbox.io/p/sandbox/tsx-bug-rl55dz

### Version

v3.12.6

### Node.js version

v16.17.0

### Package manager

yarn

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
This doesn't seem relevant here. Did you mean to file this in tsx?

**Comment by WankkoRee** [comment]
sorry, is my mistake, i dont know why I filed this here.
