### ISSUE TITLE
deno is missing?

### ISSUE THREAD

**Issue by jcayzac** [privatenumber/ts-runtime-comparison#2]
It's the elephant in the room, I think. You can't compare Typescript runtimes and just leave the main one out.

**Comment by privatenumber** [comment]
The runtimes compared are all drop-in replacements for Node.js. deno is not.

**Comment by devinrhode2** [comment]
I think it'd be useful to include deno in at least a footnote..

**Comment by privatenumber** [comment]
Why?

**Comment by devinrhode2** [comment]
Idk, as tsx becomes more popular, a percentage of people will end up asking the same question in this thread

I'm not going to try and convince you but people generally would want this.
