### ISSUE TITLE
Add notes about `ts-node`'s "experimentalResolver" option

### ISSUE THREAD

**Issue by forivall** [privatenumber/ts-runtime-comparison#5]
I discovered ts-node's hidden [`experimentalResolver`](https://github.com/TypeStrong/ts-node/issues/1514) option, and it seems like it supports _some_ of the features of "paths", etc. It's unclear which exact features they support from the [Resolution Comparison](https://github.com/privatenumber/ts-runtime-comparison#resolution), but it's worth some exploration IMO, and worth noting with an asterisk `*`.

**Comment by privatenumber** [comment]
In their latest release, [they're clear about not supporting it](https://github.com/TypeStrong/ts-node/tree/v10.9.1#paths-and-baseurl).

The latest status update on `experimentalResolver` flag is that they only support TypeScript's new extensions `.cjs` -> `.cts`, `.mjs` -> `.mts`, `.js` -> `.ts`

They'll need to support this in `tsconfig.json#paths` as well, but doesn't seem like it's implemented yet and hasn't been actively developed (no commits for 2 years): https://github.com/TypeStrong/ts-node/pull/1515

Happy to update once it's landed in a stable release.
